name = "global_value"
version = "1.0.0"
description = "Create singleton values accessible anywhere in your application."
licences = ["Apache-2.0"]
repository = { type = "github", user = "lpil", repo = "global-value" }
links = [
  { title = "Sponsor", href = "https://github.com/sponsors/lpil" },
]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
exception = ">= 2.1.0 and < 3.0.0"
